name: 🐛 Report bugs in English
description: Use English to report bugs
labels: ['bug:need-confirm']
body:
  - type: markdown
    attributes:
      value: |
        👋🏻👋🏻👋🏻Hi, thanks very much for your support to sdm2, it is really important!

        ⚠️⚠️⚠️Please read the following before submitting a bug report:
        - Before submitting a bug, you can find a solution through [README.md](https://github.com/JOU-amjs/sdm2/blob/main/README.md);
        - Make sure you have searched for [historical issues](https://github.com/JOU-amjs/sdm2/issues) and found no similar issues.
        - If you have a question or doubt, you can move to [Discussions](https://github.com/JOU-amjs/sdm2/discussions) to post, which will help maintainers manage sdm2 community better.

  - type: textarea
    id: description
    attributes:
      label: Please describe the bug in detail
      description: Please describe in as much detail as possible under what circumstances, what problems you encountered, and what solutions you have tried, including key code snippets.
    validations:
      required: true

  - type: input
    id: reproduce
    attributes:
      label: Reproduce link
      description: This helps solvers solve problems faster, you can create a repository link on [codesandbox](https://codesandbox.io), [stackBlitz](https://stackblitz.com) or GitHub. Please do not fill in invalid links.

  - type: textarea
    id: reproduce-steps
    attributes:
      label: steps to reproduce
      description: Please provide the simplest operation steps so that we can quickly reproduce the problem.
      placeholder: |
        For example: how about the parameters passed in?
    validations:
      required: true

  - type: textarea
    id: expect
    attributes:
      label: expected performance
      description: Please use clear and concise language to describe what effect you want to achieve

  - type: input
    id: version
    attributes:
      label: sdm2 version
      description: Please fill in the version number in node_modules/sdm2/package.json
      placeholder: e.g. 1.1.0
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Reproduce environment
      description: In what environment is it reproduced, please provide the version number for nodejs, and for the browser, please provide the browser manufacturer and version number

  - type: textarea
    id: remark
    attributes:
      label: additional instructions
      description: If there are additional instructions or notes, please fill them in here.
