name: 🐛用中文反馈bug
description: 使用中文反馈bug
labels: ['bug:need-confirm']
body:
  - type: markdown
    attributes:
      value: |
        👋🏻👋🏻👋🏻Hi你好，非常感谢你对sdm2的支持，它真的很重要！

        ⚠️⚠️⚠️在提交 bug 报告前，请阅读以下内容：
        - 提交bug前可先通过 [README.md](https://github.com/JOU-amjs/sdm2/blob/main/README.md) 寻找解决办法;
        - 确认你搜索过 [历史 issue](https://github.com/JOU-amjs/sdm2/issues)，并且没有发现同样的问题。
        - 如果是一个问题或疑惑，可移步到 [Discussions](https://github.com/JOU-amjs/sdm2/discussions) 发帖，这有助于作者更好地打理sdm2社区。

  - type: textarea
    id: description
    attributes:
      label: 请详细描述bug
      description: 请尽量详细地描述你在什么情况下，遇到了什么问题，以及你尝试过什么解决方法，可提供关键代码片段。
    validations:
      required: true

  - type: input
    id: reproduce
    attributes:
      label: 复现链接
      description: 这有助于解决者更快地解决问题，你可以在 [codesandbox](https://codesandbox.io)、[stackBlitz](https://stackblitz.com) 或 GitHub 上创建仓库链接。请不要填写无效的链接。

  - type: textarea
    id: reproduce-steps
    attributes:
      label: 复现步骤
      description: 请提供一个最简单的操作步骤，方便我们快速复现问题。
      placeholder: |
        比如：传入的参数如何？
    validations:
      required: true

  - type: textarea
    id: expect
    attributes:
      label: 期望的表现
      description: 请使用清晰简洁地语言描述一下期望达成什么效果

  - type: input
    id: version
    attributes:
      label: sdm2 版本
      description: 请填写 node_modules/sdm2/package.json 里的版本号
      placeholder: 比如 1.1.0
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: 复现环境
      description: 在什么环境下复现，nodejs请提供版本号，在浏览器中请提供浏览器厂商和版本号

  - type: textarea
    id: remark
    attributes:
      label: 额外的说明
      description: 如果还有额外的说明或备注，请在此填写。
