name: 🚀新特性提案
description: 对sdm2的新特性或优化提案
labels: ['feature-request']
body:
  - type: markdown
    attributes:
      value: |
        👋🏻👋🏻👋🏻Hi你好，非常感谢你对sdm2的支持，它真的很重要！

        ⚠️⚠️⚠️在提交新特性提案前，请阅读以下内容：
        - 确认目前无法通过 API 实现，可先在[README.md](https://github.com/JOU-amjs/sdm2/blob/main/README.md)中寻找可用的参数，一般来说，我们只考虑现有 API 无法轻松解决的问题的情况下添加新特性。
        - 确认在 [历史 issue](https://github.com/JOU-amjs/sdm2/issues)或[Discussion](https://github.com/JOU-amjs/sdm2/discussions)没有发现重复内容。

  - type: textarea
    id: description
    attributes:
      label: 需要新特性解决什么问题？
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: 你期望的新特性应该如何呈现？
      description: 可提供一段新特性的代码设计片段，以表达你期望的新特性如何呈现在新版本中。
